apiVersion: apps/v1
kind: Deployment
metadata:
 name: chat-service
 labels:
  app: chat-service
spec: 
 replicas: 1
 selector:
  matchLabels:
   app: chat-service
 template:
  metadata:
   labels:
    app: chat-service
  spec:
   containers:
   - name: chat-service
     image: frmnj/taptalk-chat-service:latest
     imagePullPolicy: Always
     ports: 
     - containerPort: 8765
     resources:
       requests:
         cpu: "100m"
         memory: "128Mi"
       limits:
         cpu: "500m"
         memory: "256Mi"
   - name: redis
     image: redis:alpine3.20
     ports:
     - containerPort: 6379
     resources:
       requests:
         cpu: "50m"
         memory: "64Mi"
       limits:
         cpu: "200m"
         memory: "128Mi"
