apiVersion: v1
kind: Service
metadata:
  name: censor-service
spec:
  selector:
    app: censor-service  # Debe coincidir con las labels del Deployment
  ports:
    - protocol: TCP
      port: 80        # Puerto del Service
      targetPort: 8080  # Puerto del contenedor
  type: ClusterIP  # Use ClusterIP for internal access; expose externally only via Ingress