services:
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - redis
    container_name: chat-service
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: redis-service
  taptalk-web:
    build:
      context: ./tap-talk-front
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000" 