services:
  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - redis
    container_name: chat-service

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: redis-service