name: Build and publish censor service image
on:
  push:
    paths:
      - censor-service/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      working-directory: ./censor-service
      run: docker build --file Dockerfile --tag frmnj/taptalk-censor-service:latest .

    - name: Docker Hub Login
      run: docker login -u frmnj -p ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: |
        docker push frmnj/taptalk-censor-service:latest